name: skinmatch_new
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shimmer: ^3.0.0
  dio: ^5.4.0
  shared_preferences: ^2.3.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  permission_handler: ^10.0.0
  camera: ^0.10.5+5
  arkit_plugin: ^1.1.2
  path_provider: ^2.1.1
  google_mlkit_face_detection: ^0.9.0
  photo_manager: ^3.0.0
  flutter_svg: ^2.0.7
  dropdown_button2: ^2.3.9
  fl_chart: ^0.66.0
  lottie: ^1.2.1
  pie_chart: ^5.3.2
  cached_network_image: ^3.3.1 
  uuid: ^4.0.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

l10n:
  arb-dir: lib/l10n  
  template-arb-file: app-en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
